### ISSUE TITLE
Replace internal `Source` and mass mixing classes with models from snewpy.

### ISSUE THREAD

**Issue by sybenzvi** [icecube/ASTERIA#60]
Since [snewpy](https://github.com/SNEWS2/snewpy) has standardized access to a number of CCSN models and flavor transformation scenarios, we should pull it in as a dependency. This would entail deleting the `Source` class in the `source` module, but keeping the functionality of the `photonic_energy_per_vol` member function.

About flavor transformations, we can probably completely remove the `oscillations` module and use the transformation classes implemented in snewpy.

**Comment by sgriswol** [comment]
Resolved by #62
